languageCode = 'en-us'
title = 'AWS SecurityHub Suppression'
theme = "hugo-theme-learn"
baseURL = "http://localhost:1313"


[params]
disableLandingPageButton = "true"

[outputs]
home = [ "HTML", "RSS", "JSON"]